rrbot:
  joint_state_controller:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint1
    pid: {p: 100.0, i: 0.01, d: 10.0}
    interface_name: position

  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0.01, d: 10.0}
    interface_name: position
