xolobot_arm:
  ros_parameters: 
    update_rate: 100

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

  joint_trajectory_controller:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - jnt_pecho_hombro
      - jnt_hombro_hombro
      - jnt_hombro_biceps
      - jnt_biceps_codo
      - jnt_codo_antebrazo
      - jnt_palma_pulgar_1
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: jnt_pecho_hombro
    pid:
      p: 100.0 
      i: 0.01
      d: 10.0
    interface_name: "position"
      
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: jnt_hombro_hombro
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
    interface_name: "position"

  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: jnt_hombro_biceps
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
    interface_name: "position"
  
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: jnt_biceps_codo
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
    interface_name: "position"
    
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: jnt_codo_antebrazo
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
    interface_name: "position"
    
  joint6_position_controller:
    #type: effort_controllers/JointPositionController
    type: position_controllers/JointPositionController
    joint: jnt_palma_pulgar_1
    pid:
      p: 100.0
      i: 0.01
      d: 10.0
    interface_name: "position"
