controller_manager:
  ros__parameters:
    update_rate: 1000

    # Controlador para publicar el estado de las articulaciones
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Controlador para mover el robot a una posición deseada en varias articulaciones
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController 
      ros__parameters:
        joints:
          - jnt_pecho_hombro
          - jnt_hombro_hombro
          - jnt_hombro_biceps
          - jnt_biceps_codo
          - jnt_codo_antebrazo
        command_interfaces:
          - position  
        state_interfaces:
          - position  
          - velocity
