controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    position_controller:
      type: "position_controllers/JointPositionController"
      ros__parameters:
        joints:
          - jnt_pecho_hombro
          - jnt_hombro_hombro
          - jnt_hombro_biceps
          - jnt_biceps_codo
          - jnt_codo_antebrazo
          - jnt_palma_pulgar_1
        command_interfaces:
          - position  
        state_interfaces:
          - position  
          - velocity
