controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      ros__parameters:
        joints: 
          - arm_base
          - base_to_arm
        command_interfaces: 
          - position
        state_interfaces: 
          - position
          - velocity