controller_manager:
  ros__parameters:
    update_rate: 1000

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      ros__parameters:
        joints: 
          - jnt_pecho_hombro
          - jnt_hombro_hombro
          - jnt_hombro_biceps
          - jnt_biceps_codo
          - jnt_codo_antebrazo
          - jnt_palma_pulgar_1
        command_interfaces: 
          - position
        state_interfaces: 
          - position
          - velocity