controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_pecho_hombro
      pid:
        p: 100.0
        i: 0.01
        d: 10.0

    joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_hombro_hombro
      pid:
        p: 100.0
        i: 0.01
        d: 10.0

    joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_hombro_biceps
      pid:
        p: 100.0
        i: 0.01
        d: 10.0

    joint4_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_biceps_codo
      pid:
        p: 100.0
        i: 0.01
        d: 10.0

    joint5_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_codo_antebrazo
      pid:
        p: 100.0
        i: 0.01
        d: 10.0

    joint6_position_controller:
      type: effort_controllers/JointPositionController
      joint: jnt_palma_pulgar_1
      pid:
        p: 100.0
        i: 0.01
        d: 10.0
